//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://opendata.smhi.se/xsd/portal.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="https://opendata.smhi.se/xsd/portal.xsd", IsNullable=false)]
public partial class api {
    
    private System.DateTime updatedField;
    
    private string titleField;
    
    private string summaryField;
    
    private linkType[] linkField;
    
    private linksType[] categoryField;
    
    /// <remarks/>
    public System.DateTime updated {
        get {
            return this.updatedField;
        }
        set {
            this.updatedField = value;
        }
    }
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string summary {
        get {
            return this.summaryField;
        }
        set {
            this.summaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("link")]
    public linkType[] link {
        get {
            return this.linkField;
        }
        set {
            this.linkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("category")]
    public linksType[] category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://opendata.smhi.se/xsd/portal.xsd")]
public partial class linkType {
    
    private string relField;
    
    private string typeField;
    
    private string hrefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rel {
        get {
            return this.relField;
        }
        set {
            this.relField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string href {
        get {
            return this.hrefField;
        }
        set {
            this.hrefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://opendata.smhi.se/xsd/portal.xsd")]
public partial class geoBox {
    
    private double minLatitudeField;
    
    private double minLongitudeField;
    
    private double maxLatitudeField;
    
    private double maxLongitudeField;
    
    /// <remarks/>
    public double minLatitude {
        get {
            return this.minLatitudeField;
        }
        set {
            this.minLatitudeField = value;
        }
    }
    
    /// <remarks/>
    public double minLongitude {
        get {
            return this.minLongitudeField;
        }
        set {
            this.minLongitudeField = value;
        }
    }
    
    /// <remarks/>
    public double maxLatitude {
        get {
            return this.maxLatitudeField;
        }
        set {
            this.maxLatitudeField = value;
        }
    }
    
    /// <remarks/>
    public double maxLongitude {
        get {
            return this.maxLongitudeField;
        }
        set {
            this.maxLongitudeField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(parameterLinksType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(geoLinksType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://opendata.smhi.se/xsd/portal.xsd")]
public partial class linksType {
    
    private string keyField;
    
    private System.DateTime updatedField;
    
    private string titleField;
    
    private string summaryField;
    
    private linkType[] linkField;
    
    /// <remarks/>
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime updated {
        get {
            return this.updatedField;
        }
        set {
            this.updatedField = value;
        }
    }
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string summary {
        get {
            return this.summaryField;
        }
        set {
            this.summaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("link")]
    public linkType[] link {
        get {
            return this.linkField;
        }
        set {
            this.linkField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://opendata.smhi.se/xsd/portal.xsd")]
public partial class parameterLinksType : linksType {
    
    private string unitField;
    
    private geoBox geoBoxField;
    
    /// <remarks/>
    public string unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    public geoBox geoBox {
        get {
            return this.geoBoxField;
        }
        set {
            this.geoBoxField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://opendata.smhi.se/xsd/portal.xsd")]
public partial class geoLinksType : linksType {
    
    private geoBox geoBoxField;
    
    /// <remarks/>
    public geoBox geoBox {
        get {
            return this.geoBoxField;
        }
        set {
            this.geoBoxField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://opendata.smhi.se/xsd/portal.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="https://opendata.smhi.se/xsd/portal.xsd", IsNullable=false)]
public partial class category {
    
    private string keyField;
    
    private System.DateTime updatedField;
    
    private string titleField;
    
    private string summaryField;
    
    private linkType[] linkField;
    
    private linksType[] versionField;
    
    /// <remarks/>
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime updated {
        get {
            return this.updatedField;
        }
        set {
            this.updatedField = value;
        }
    }
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string summary {
        get {
            return this.summaryField;
        }
        set {
            this.summaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("link")]
    public linkType[] link {
        get {
            return this.linkField;
        }
        set {
            this.linkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("version")]
    public linksType[] version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://opendata.smhi.se/xsd/portal.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="https://opendata.smhi.se/xsd/portal.xsd", IsNullable=false)]
public partial class version {
    
    private string keyField;
    
    private System.DateTime updatedField;
    
    private string titleField;
    
    private string summaryField;
    
    private linkType[] linkField;
    
    private linksType[] resourceField;
    
    /// <remarks/>
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime updated {
        get {
            return this.updatedField;
        }
        set {
            this.updatedField = value;
        }
    }
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string summary {
        get {
            return this.summaryField;
        }
        set {
            this.summaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("link")]
    public linkType[] link {
        get {
            return this.linkField;
        }
        set {
            this.linkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("resource")]
    public linksType[] resource {
        get {
            return this.resourceField;
        }
        set {
            this.resourceField = value;
        }
    }
}
